blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    # Hompe page.
    path('', views.index, name='index'),
    # Page for adding a new post.
    path('new_post/', views.new_post, name='new_post'),
    # Page for editing a post.
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Ragistration page.
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User

# My models.

class BlogPost(models.Model):
    """A blog that user can write."""
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class BlogForm(forms.ModelForm):
	class Meta:
		model = BlogPost
		fields = ['title', 'text']
		label = {'title': '', 'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.shortcuts import render, redirect

# Create your views here.

from .models import BlogPost
from .forms import BlogForm
from django.contrib.auth.decorators import login_required

from django.http import Http404

def index(request):
    """The home page for blogs."""
    posts = BlogPost.objects.order_by('-date_added')
    context = {'posts': posts}
    return render(request, 'blogs/index.html', context)

@login_required
def new_post(request):
    """Add a new post."""
    if request.method != 'POST':
        form = BlogForm()
    else:
        form = BlogForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, post_id):
    """Edit a post."""
    post = BlogPost.objects.get(id=post_id)
    title = post.title
    text = post.text
    
    if post.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = BlogForm(instance=post)
    else:
        # POST data submitted; process data.
        form = BlogForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:index')

    context = {'post': post, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

# My views.

def register(request):
	"""Register a new user."""

	if request.method != 'POST':
		# Display blank registration form.
		form = UserCreationForm()
	else:
		# Process completed form.
		form = UserCreationForm(data = request.POST)

		if form.is_valid():
			new_user = form.save()

			# Log the user in and then redirect to home page.
			login(request, new_user)
			return redirect('blogs:index')

	context = {'form': form}
	return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>

      {% bootstrap_css %}
      {% bootstrap_javascript jquery='full' %}

  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4 border">
      <a class="navbar-brand" href="{% url 'blogs:index' %}">Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" 
        data-target="#navbarSupportedContent" 
        aria-controls="navbarSupportedContent" aria-expanded="false" 
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Hello, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
      </ul>

      </div>
    </nav>

    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </main>

  </body>
</html>

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h5><a href="{% url 'blogs:index' %}">Blog</a></h5>
  <h4>Edit post: {{post.title}}</h4>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'blogs:edit_post' post.id %}" method='post'>
   {% csrf_token %}
   {% bootstrap_form form %}

   {% buttons %}
      <button name="submit" class="btn btn-primary">Save changes</button>
   {% endbuttons %}
  </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <h5><a href="{% url 'blogs:new_post' %}">Add a new post</a></h5>
{% endblock page_header %}

{% block content %}

{% for post in posts %}
<div class="card mb-3">
  <div class="card-header">
    {{post.date_added|date:'M d, Y H:i'}}
    <a href="{% url 'blogs:edit_post' post.id%}">edit post</a>
  </div>
  <div class="card-body">
    <h5 class="card-title">{{post.title}}</h5>
    <p class="card-text">{{post.text|linebreaks}}</p>
  </div>
</div>
{% endfor %}

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h5><a href="{% url 'blogs:index' %}">Blog</a></h5>
  <h4>Add a new post:</h4>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'blogs:new_post' %}" method='post'>
   {% csrf_token %}
   {% bootstrap_form form %}

   {% buttons %}
      <button name="submit" class="btn btn-primary">Add post</button>
   {% endbuttons %}
  </form>

{% endblock content %}